version: '3.4'
services:
  api:
    build:
      context: .
      target: dev
    volumes: ['.:/usr/src/app']
    ports: ['5000:5000']
    links: ['redis', 'mongo']
  redis:
    image: redis
    ports: ['6379']
  mongo:
    image: mongo
    ports: ['27017:27017']
